scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4
  LeadingZero:
    enabled: true
    style: include_zero # or 'include_zero'
  Comment:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  PropertySortOrder:
    enabled: false